apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "text-classifier"
spec:
  predictor:
    sklearn:
      storageUri: "s3://your-bucket/models/text-classifier"
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
